name: Build and deploy ASP.Net Core app to Azure Web App - serenade

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Navigate to backend and update appsettings.json with Connection String
        run: |
          cd backend-asp.netCore
          $appSettingsPath = "./appsettings.json"
          $json = Get-Content -Raw -Path $appSettingsPath | ConvertFrom-Json
          $json.ConnectionStrings.DefaultConnection = "${{ secrets.DB_CONNECTION_STRING }}"
          $json | ConvertTo-Json | Set-Content -Path $appSettingsPath

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./backend-asp.netCore

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"
        working-directory: ./backend-asp.netCore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'serenade'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1234 }}
